apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: spotcord
build:
  artifacts:
  - image: registry.appjackstudio.com/spotcord/downloader
    context: downloader
    docker:
      dockerfile: Dockerfile
  - image: registry.appjackstudio.com/spotcord/bot
    context: bot
    docker:
      dockerfile: Dockerfile
  local:
    useBuildkit: true
deploy:
  kustomize:
    paths:
    - kube
