apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: spotcord
build:
  artifacts:
  - image: ghcr.io/bmxguy100/spotcord-downloader
    context: downloader
    docker:
      dockerfile: Dockerfile
  - image: ghcr.io/bmxguy100/spotcord-bot
    context: bot
    docker:
      dockerfile: Dockerfile
  local:
    useBuildkit: true
    concurrency: 0
profiles:
- name: dev
  activation:
  - command: dev
  deploy:
    kustomize:
      paths:
      - kube/dev
- name: prod
  deploy:
    kustomize:
      paths:
      - kube/prod
