apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      initContainers:
      - name: deploy-commands
        image: registry.appjackstudio.com/spotcord/bot
        command:
          - node
          - dist/deploy-commands.js
        resources:
          limits:
            memory: "128Mi"
            cpu: "1500m"
        envFrom:
          - configMapRef:
              name: bot-env-config
          - secretRef:
              name: bot-env-secret
      containers:
      - name: bot
        image: registry.appjackstudio.com/spotcord/bot
        resources:
          limits:
            memory: "128Mi"
            cpu: "1500m"
        envFrom:
          - configMapRef:
              name: bot-env-config
          - secretRef:
              name: bot-env-secret
