apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader
spec:
  selector:
    matchLabels:
      app: downloader
  template:
    metadata:
      labels:
        app: downloader
    spec:
      containers:
        - name: downloader
          image: ghcr.io/bmxguy100/spotcord-downloader
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            limits:
              memory: "256Mi"
              cpu: "1500m"
          volumeMounts:
            - name: secret
              mountPath: /secret
              readOnly: true
            - name: cache
              mountPath: /cache
            - name: temp
              mountPath: /tmp
          ports:
            - name: http
              containerPort: 5000
          startupProbe:
            failureThreshold: 10
            initialDelaySeconds: 10
            httpGet:
              port: 5000
              path: /health
      volumes:
        - name: secret
          secret:
            secretName: downloader-credentials
        - name: temp
          emptyDir:
            medium: Memory
            sizeLimit: 512Mi
        - name: cache
          emptyDir:
            sizeLimit: 5Gi
          # hostPath:
          #   path: /data/cache/spotcord
---
apiVersion: v1
kind: Service
metadata:
  name: downloader
spec:
  selector:
    app: downloader
  ports:
    - port: 80
      targetPort: http
