apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: downloader-credentials
spec:
  encryptedData:
    credentials.json: AgCCHKaQFE5s5EbiEtp0PymecJPvIXCjexvBp1lgEAHTf6H2Am2adA34H1TKaAuOL1VcTltTJpTP99lYZ6yNFY4CYZXd1IiZ+IXgWdaZdVIyjpcM7tTHGvRAomdAdd4L/JAdc55LXpOVy5EksAzLnCrNRX8/BiR/w7RtzSwOUC+VES79fb/afzHCTW2orD+N90TcnKp9wNuDgfnop4I2TVaibnuXVaItBKbxsK24V9jSwxyV0+2xjTFKJXzvjnJdHzX6ah8Mjp9ZxWAw2U3S2E2B2UsR420v4SrP7d08p1Nv796ctzBf3yVJOceUnvI0n0XII54qcUuAuOaoFDNgRMwdl2a2rEugTG+izsO3T8pMTZLjeNit1yWNxS5s53VddlrxUI4w5Fci+p0s9A4XPhK0jQvSv+e6UlSLKYYfnAE+xnswTFnc7gbJReuWk1wXb/DOHElKDIeCJlQCzhPY66wc9sKPWKEgxNCEkSTglQQ7N4+oGwsYxQKdaZTr2Um+/bG20F1b2/n40B/m1fkP9/wMGTPaYCRsnf1o56qdR+JZoioL9IlqCS9ds6mN+3YewXDiUlAIN2RJref0IiwzT1afSxvnm8SG2C3pYE3/vYn3/M/nYMqNs7ThMBE2PjBmRF8N8Mk+LcsQK6ucFnfigw2sra8b8kNRYk30GdT2pntNgVbdBjiMk/WpflHwQ7+tUam4tsEJjqxZd3/0D6hwVq5jnDi5oGb/At/h0M05TPlsGQB+x5eixqlNaS4bdm94RVeEJ6aGFmj4rUdtp992eNJGDozp5Yq10s3woDeUJZ5vA0ceRAS+lRF30RJ9KjKALiQcbZIhTh5dtdOjh3q/4uSeL4Uk+cRZ0z62xF/ckentRnIbEkV9q+0D5HFbsGcSFnE3BvuHsnJ0PfkNmJgii8/YLREhYhET7tkzHaGJ4frEDP2f2hSNGFpFIa5nr1YKpfm/Ewh22IscOXrRcXWqk1MHV68n7xVDQGIrzB3v3Aby1zlaKwiF40Hygieu1RhDbpjmisl+nAyCVSa0sdDokgn6UccULpCESFogJjTFsCas4bq6B6saNeZp4aMVkSVY/v4th2XLRM41x+PHDMXzoz/fP+VjjqKeEQyRw9nk5Pp3iq0bznMlNA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: downloader-credentials
    type: Opaque
