apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: registry.appjackstudio.com/spotcord/bot
        resources:
          limits:
            memory: "128Mi"
            cpu: "1500m"
        envFrom:
          - secretRef:
              name: bot-env
