name: ci

on:
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install skaffold
        run: |
          sudo curl -Lo /usr/bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo chmod a+x /usr/bin/skaffold

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build Docker images
        run: skaffold build -p prod --tag='v${{ github.run_number }}' --push

      - name: Update image digests
        run: yq -i '.images[].newTag = "v${{ github.run_number }}"' kube/prod/kustomization.yaml

      - name: Commit file
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            kube/prod/kustomization.yaml
          commit-message: Update Image Tags
          ref: refs/heads/release
