name: ci

on:
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build Docker images
        uses: hiberbee/github-action-skaffold@1.12.0
        with:
          skaffold-version: v1.36.0
          command: build
          profile: prod
          push: true
          tag: v${{ github.run_number }}

      - name: Update image digests
        run: yq -i '.images[].newTag = v${{ github.run_number }}' kube/prod/kustomization.yaml

      # Note: pushes run from inside github actions do not cause an infinite loop
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update image tags
          branch: release
          file_pattern: kube/prod/kustomization.yaml
          push_options: "--force"
